# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Alessio Periloso's Resume
tagline:             Insert here your tagline if you need it.
url:                 http://periloso.github.io/Resume
#paginate:            1
baseurl:             "http://periloso.github.io/Resume"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Alessio Periloso
  url:               http://periloso.com/
  email:             b1galez@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/periloso/Resume

# Collections
collections:
  - previous_employments
  - contents