# Site settings
title: Alessio Periloso Curricula Engine.
email: b1galez@gmail.com
description: "Curricula Engine allows you to easy deploy your resume!"
baseurl: "/"
url: "http://resume.periloso.com"
paginate: 2
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
permalink: pretty
relative_permalinks: true

# Collections
collections:
  - current_positions
  - education
  - languages
  - other_information
  - previous_employments
  - skills
  - photo
